[features]
seeds = false
skip-lint = false
[programs.devnet]
grading_system = "4CXvM9ENhCMGsfz7YPjqDjAkqwLqMwTvw3SBq3YChBNN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mateo/.config/solana/id.json"