[features]
seeds = false
skip-lint = false

[programs.devnet]
grading_system = "5GZTR4UtisYrZ8aUN3gsUisMESbMKBMgdbkZezzKouQs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
init_main_account = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init_main_account.ts"
init_school = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init_school.ts"
init_student = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init_student.ts"
set_note = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/set_note.ts"